ENVIRONMENT_VARIABLES:
    MAIN_URL: "https://undraw.co/illustrations"
    SECOND_URL: "https://undraw.co/api/illustrations"
    PAGE_EXT: "?page="
    PAGE_COUNT: 3
    SCRAPER_THREAD_COUNT: 1
    DOWNLOAD_THREAD_COUNT: 10
    CLASS_NAME_SVG: "ClassicGrid__Media-sc-td9pmq-2 ffqsDq"
    CLASS_NAME_TITLE: "ClassicGrid__Content-sc-td9pmq-3 jCxkJm"
    IMAGE_DIR: "../images"

QUEUES:
    Q1: "scraper_q"
    Q2: "download_q"

WORKERS:
    SCRAPER_WORKER:
        ID: "SCRAPER_WORKER"
        CLASS: "ScrapeScheduler"
        INPUT_QUEUE: "scraper_q"
        OUTPUT_QUEUE: "download_q"
        LOCATION: "schedulers"
        THREAD_COUNT: 1

    DOWNLOAD_WORKER:
        ID: "DOWNLOAD_WORKER"
        CLASS: "DownloadScheduler"
        INPUT_QUEUE: "download_q"
        OUTPUT_QUEUE: ""
        LOCATION: "schedulers"
        THREAD_COUNT: 10

CLASSES:
    NAME: "UnDraw"
    LOCATION: "undraw"


UTIL_FUNCTIONS:
    DOWNLOAD_IMG:
      NAME: "download_img"
      LOCATION: "utils"

    GET_SOUP:
      NAME: "get_soup"
      LOCATION: "utils"



